trigger:
  branches:
    include:
      - main

pool:
  name: default

variables:
  S3_BUCKET_NAME: 'azuredevops-test1'
  SOURCE_DIR: '$(Build.SourcesDirectory)'

steps:
- checkout: self

- script: |
    pip install awscli
    aws configure set aws_access_key_id %AWS_ACCESS_KEY_ID%
    aws configure set aws_secret_access_key %AWS_SECRET_ACCESS_KEY%
    aws s3 sync "%SOURCE_DIR%" "s3://%S3_BUCKET_NAME%" --delete
  env:
    AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
    AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
  displayName: 'Upload to S3'
